services:
  bot:
    command: './main start-bot --bot-token=${BOT_TOKEN} --sentry-dsn=${SENTRY_DSN} --mixpanel-token=${MIXPANEL_TOKEN}'
    image: kalys/tiligram:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./bleve.search:/root/bleve.search

  api:
    command: './main start-api --sentry-dsn=${SENTRY_DSN} --cors-origin=${CORS_ORIGIN}'
    image: kalys/tiligram:latest
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./bleve.search:/root/bleve.search
